drop table if exists to_do_entries_domain CASCADE; 
drop table if exists to_do_lists_domain CASCADE; 
create table to_do_entries_domain (id bigint generated by default as identity, description varchar(255) not null, due_date date not null, my_list_id bigint, primary key (id));
create table to_do_lists_domain (id bigint generated by default as identity, title varchar(255) not null, primary key (id));
alter table to_do_entries_domain add constraint FK87dy1e3cw8ouiqibxd8giwmwy foreign key (my_list_id) references to_do_lists_domain on delete cascade;

